# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source code
COPY tsconfig.json ./
COPY src ./src

# Build
RUN npm run build

# Default command
CMD ["node", "dist/index.js"]
